name: powervideo
description: "Mobile-Based Attendance Management System using Geofencing and Facial Recognition"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  http: ^1.4.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  go_router: ^15.1.2
  flutter_screenutil: ^5.9.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  camera: ^0.11.1
  image_picker: ^1.1.2
  geolocator: ^14.0.1
  permission_handler: ^12.0.0+1
  intl: ^0.20.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.15
  riverpod_generator: ^2.6.3
  hive_generator: ^2.0.1
  json_serializable: ^6.9.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png